project:
  type: website
  output-dir: docs
  
website:
  title: "Jay Kulkarni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        menu: 
          - text: "About me"
            href: about.qmd
          - text: "CV"
            href: MISC/KulkarniCVOct2023.pdf
      - blog.qmd
           
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

